---
title: "Inputs to flows"
author: "Emil De Borger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
install.packages("openxlsx")
require(openxlsx)
require(dplyr)
require(tidyr)
```


## Read input matrix
```{r}
## Read input file.
mat <- read.xlsx(xlsxFile = "testmatrix.xlsx", sheet = "Sheet1", fillMergedCells = TRUE, colNames = TRUE)

## Convert everything not "x" to NA.
mat[,-1][mat[,-1] != "x"] <- NA

```


## Needed functions
```{r}
## Replace NA and x with NA.
seller <- function(x){
  ss <- x[!is.na(x)]
  if(length(ss) > 0){
    out <- 1
  } else{
    out <- 0
  }
  return(out)
}

## Flow writer function
floWrite <- function(df) {
  ## Filter rows/columns with duplicates
  df <- apply(df, MARGIN = 2, FUN = function(x) tapply(x, factor(df[,1]), FUN = seller))
  df <- t(apply(df, MARGIN = 1, FUN = function(x) tapply(x, colnames(df), FUN = sum)))
  df <- df[, colnames(df) != "X1"]
  
  ## Loop over columns to write long vector with flows
  flows <- NULL
  for(i in 1:length(colnames(df))){
    dat <- df[,i]
    prey <- names(dat[dat!= 0])
    flowsnew <- paste0(prey, "->", colnames(df)[i])
    flowsnew <- c(paste0("!Flows to ", colnames(df)[i]), flowsnew, "")
    flows <- c(flows, flowsnew)
  }
  return(flows)
}
```


## Run function
```{r}
testflows <- floWrite(mat)
write.table(testflows, "flowstest.txt", row.names = FALSE, quote = FALSE)
```